export const eventType = {
  name: 'event',
  title: 'Event',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'startDate',
      title: 'Start Date',
      type: 'datetime',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'endDate',
      title: 'End Date',
      type: 'datetime',
    },
    {
      name: 'location',
      title: 'Location (City, State)',
      type: 'string',
    },
    {
      name: 'logo',
      title: 'Event Logo',
      type: 'image',
      options: { hotspot: true },
    },
    {
      name: 'heroImage',
      title: 'Hero Background Image',
      type: 'image',
      options: { hotspot: true },
    },
    {
      name: 'brandColor',
      title: 'Brand Color (Hex Code)',
      type: 'string',
      description: 'e.g. #FF0000',
    },
    {
      name: 'signUpLink',
      title: 'Sign Up / RSVP Link',
      type: 'url',
    },
    {
      name: 'videoIds',
      title: 'Related YouTube Video IDs',
      description: 'Array of YouTube Video IDs (e.g., dQw4w9WgXcQ)',
      type: 'array',
      of: [{ type: 'string' }],
      initialValue: [],
    },
    {
      name: 'articleUrls',
      title: 'Related Substack Article URLs',
      description: 'Array of full Substack URLs',
      type: 'array',
      of: [{ type: 'url' }],
      initialValue: [],
    },
    {
      name: 'tags',
      title: 'Content Matching Tags',
      description: 'Exact string tags to match against YouTube and Substack titles/descriptions (e.g., "#SDCC 2026").',
      type: 'array',
      of: [{ type: 'string' }],
      initialValue: [],
    },
  ],
};
